# This workflow will build and push a Docker container to the Environments (in Azure ML studio).
name: Build and register an environment in Azure ML Studio.

# Enable a workflow to be triggered manually using the GitHub API, GitHub CLI, or GitHub browser interface.
on: workflow_dispatch

env:
  CONTAINER_NAME: ${{ "{{" }} secrets.RESOURCE_GROUP_NAME {{ "}}" }}-env

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev # This is the name of the Environment you will create in this Repository (see README_Environment.md).
    name: Build and register environment
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure container registry
        uses: azure/docker-login@v1
        with:
          username: ${{ "{{" }} secrets.REGISTRY_USERNAME {{ "}}" }}
          password: ${{ "{{" }} secrets.REGISTRY_PASSWORD {{ "}}" }}
          login-server: ${{ "{{" }} vars.AZURE_CONTAINER_REGISTRY_NAME {{ "}}" }} # ensure your login-server matches the fully qualified path to your image

      - name: Build and push container image to registry
        run: |
          DOCKER_BUILDKIT=1 docker build \
          -t "${{ "{{" }}env.CONTAINER_NAME{{ "}}" }}" \
          -f docker/Dockerfile.environment \
          --build-arg ssh_prv_key="${{ "{{" }} secrets.SSH_KEY {{ "}}" }}" \
          --build-arg ssh_prv_key_sub="${{ "{{" }} secrets.SSH_KEY {{ "}}" }}" \
          --build-arg ssh_ml_utils="${{ "{{" }} secrets.SSH_KEY {{ "}}" }}" \
          --build-arg git_branch_name="${{ "{{" }} github.ref_name {{ "}}" }}" \
          --build-arg git_repository_name="${{ "{{" }} github.event.repository.name {{ "}}" }}" .
          docker tag "${{ "{{" }}env.CONTAINER_NAME}}" "${{ "{{" }} vars.AZURE_CONTAINER_REGISTRY_NAME {{ "}}" }}/environments/${{ "{{" }}env.CONTAINER_NAME{{ "}}" }}:latest"
          docker push "${{ "{{" }} vars.AZURE_CONTAINER_REGISTRY_NAME {{ "}}" }}/environments/${{ "{{" }}env.CONTAINER_NAME{{ "}}" }}:latest"
      # - name: Log in with Azure
      #   uses: azure/login@v1
      #   with:
      #     tenant-id: ${{ "{{" }} secrets.TENANT_ID {{ "}}" }}
      #     client-id: ${{ "{{" }} secrets.SERVICE_PRINCIPAL {{ "}}" }}
      #     subscription-id: ${{ "{{" }} secrets.SUBSCRIPTION_ID {{ "}}" }}
      # - name: Run Azure CLI script
      #   uses: azure/CLI@v2
      #   with:
      #     azcliversion: 2.38.0
      #     inlineScript: |
      #       az extension add -n azure-cli-ml --yes
      #       if az ml environment list -w "${{ "{{" }} secrets.WORKSPACE_NAME {{ "}}" }}" -g "${{ "{{" }} secrets.RESOURCE_GROUP_NAME {{ "}}" }}" | grep -q "${{ "{{" }}env.CONTAINER_NAME{{ "}}" }}"; then echo "Environment already registered!!!"; else az ml environment create --name "${{ "{{" }}env.CONTAINER_NAME{{ "}}" }}" -i "${{ "{{" }} env.CONTAINER_NAME {{ "}}" }}/environments/${{ "{{" }}env.CONTAINER_NAME{{ "}}" }}:latest" -w "${{ "{{" }} secrets.WORKSPACE_NAME {{ "}}" }}" -g "${{ "{{" }} secrets.RESOURCE_GROUP_NAME {{ "}}" }}"; fi
